name: CI PPP

# gatilhos 
on: 
  workflow_dispatch:

jobs: 
  testes:

    #[config do SO]  (windows/linux/mac, chrome/firefox/edge, ...)
    runs-on: ubuntu-latest

    #[variaveis] (variáveis de ambiente, chaves de acesso a plataformas, etc...)
    env: 
      API_BASE_URL: 'http:localhost:3000'
      PORT: 4000

    # [acoes ou passsos]
    steps: 

      - name: Checkout do Repositoriio
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm install

      - name: Iniciar o servidor de aplicação
        run: npm start

      - name: Executar os testes
        run: npm test
