name: CI Projeto de Portfólio Pessoal

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 3000

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm install

      - name: Iniciar o servidor de aplicação
        run: npm start &

      - name: Esperar o servidor subir
        run: npx wait-on http://localhost:3000

      - name: Executar os testes
        run: npm test

      - name: Merge dos relatórios Mochawesome
        run: npx mochawesome-merge mochawesome-report/*.json > mochawesome-report/merged.json

      - name: Gerar relatório HTML final
        run: npx marge mochawesome-report/merged.json -f report -o mochawesome-report

      - name: Upload do relatório Mochawesome
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/

      - name: Finalizar servidor Node.js
        if: always()
        run: pkill node || true