name: CI API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: 'http://localhost:3000'

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm install

      - name: Iniciar o servidor de aplicação
        run: npm start &

      - name: Executar os testes
        run: npm run test

      - name: Listar arquivos do relatório
        run: ls -R test/cypress/reports/ || echo "Diretório não encontrado"

      - name: Upload do relatório Mochawesome
        uses: actions/upload-artifact@v4
        if: always() # Executa mesmo se os testes falharem
        with:
          name: mochawesome-report
          path: test/cypress/reports/

      - name: Validar sucesso dos testes
        run: |
          FAILURES=$(jq '.stats.failures' test/cypress/reports/mochawesome.json)
          if [ "$FAILURES" -gt 0 ]; then
            echo "❌ Testes falharam: $FAILURES falhas encontradas"
            exit 1
          else
            echo "✅ Todos os testes passaram"
          fi

      - name: Finalizar servidor Node.js
        if: always()
        run: pkill node || true