name: CI Projeto de Portfólio Pessoal

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  test:
    # Config do SO (windows/linux/mac, chrome/firefox/edge, ...)
    runs-on: ubuntu-latest

    # Variáveis de ambiente
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 3000

    # Ações ou passos
    steps:
      # Projetos (aplicações, projeto de teste, etc...)
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # Dependências do projeto (node/npm, java/maven, gradle, python/pip, ...)
      - name: Instalando as dependências
        run: npm install

      - name: Iniciar o servidor de aplicação
        run: npm start &

      - name: Executar os testes
        run: npm test

      - name: Upload do relatório Mochawesome
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
